{% set name = "django_coverage_plugin" %}
{% set version = "1.5.1a0" %}
{% set sha256 = "81d425807d8fa8ecff04099b5058cac280ba0ed0a53da87c3325a01268f8f25b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - django >=1.8
    - coverage >=4.0
    - six >=1.4.0

about:
  home: https://github.com/nedbat/django_coverage_plugin
  license: Apache 2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A plugin for coverage.py to measure Django template execution'
  description: 
    A coverage.py plugin to measure the coverage of Django templates.
    Supported Python versions are 2.7, 3.4, 3.5 and 3.6.
    Supported Django versions are 1.8 through 1.11.
    Supported coverage.py versions are 4.0 and higher.
  doc_url: http://coverage.readthedocs.io/en/latest/plugins.html
  dev_url: https://github.com/nedbat/django_coverage_plugin

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
