{% set name = "django_coverage_plugin" %}
{% set version = "3.1.0" %}
{% set sha256 = "223d34bf92bebadcb8b7b89932480e41c7bd98b44a8156934488fbe7f4a71f99" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=1.8
    - coverage >=4.0

test:
  imports:
    - django_coverage_plugin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nedbat/django_coverage_plugin
  license: Apache-2.0
  license_family: Apache
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A plugin for coverage.py to measure Django template execution
  description: A coverage.py plugin to measure the coverage of Django templates. Supported Python versions are 2.7, 3.4, 3.5 and 3.6. Supported Django versions are 1.8 through 1.11. Supported coverage.py versions are 4.0 and higher.
  doc_url: http://coverage.readthedocs.io/en/latest/plugins.html
  dev_url: https://github.com/nedbat/django_coverage_plugin

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
